language: cpp

os:
  - linux
  - osx


compiler:
  - clang
  - gcc

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
- sudo add-apt-repository -y ppa:team-xbmc/ppa ;
- sudo apt-get update -qq ;
- sudo apt-get install -y  libsdl2-dev ;
- sudo apt-get install freeglut3-dev ;
- fi

script: pwd && ls && cmake . && make && ls && cat Makefile && cd bin && pwd && ls
